// Mall Part

export const MALL_SIGNUP_BEGIN = "MALL_SIGNUP_BEGIN";
export const MALL_SIGNUP_SUCCESS = "MALL_SIGNUP_SUCCESS";
export const MALL_SIGNUP_FAIL = "MALL_SIGNUP_FAIL";

export const SIGNUP_BEGIN = "SIGNUP_BEGIN";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_TOKEN = "SET_TOKEN";

export const LOGOUT_USER = "LOGIN_FAIL";

export const GET_MALL_BEGIN = "GET_MALL_BEGIN";
export const GET_MALL_SUCCESS = "GET_MALL_SUCCESS";
export const GET_MALL_FAIL = "GET_MALL_FAIL";

export const GET_BRAND_BEGIN = "GET_BRAND_BEGIN";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAIL = "GET_BRAND_FAIL";

export const GET_MALL_AUTH_BEGIN = "GET_MALL_AUTH_BEGIN";
export const GET_MALL_AUTH_SUCCESS = "GET_MALL_AUTH_SUCCESS";
export const GET_MALL_AUTH_FAIL = "GET_MALL_AUTH_FAIL";

export const UPDATE_MALL_BEGIN = "UPDATE_MALL_BEGIN";
export const UPDATE_MALL_SUCCESS = "UPDATE_MALL_SUCCESS";
export const UPDATE_MALL_FAIL = "UPDATE_MALL_FAIL";

export const UPDATE_MALL_STORE_BEGIN = "UPDATE_MALL_STORE_BEGIN";
export const UPDATE_MALL_STORE_SUCCESS = "UPDATE_MALL_STORE_SUCCESS";
export const UPDATE_MALL_STORE_FAIL = "UPDATE_MALL_STORE_FAIL";

export const ADD_MALL_STORE_BEGIN = "UPDATE_MALL_STORE_BEGIN";
export const ADD_MALL_STORE_SUCCESS = "UPDATE_MALL_STORE_SUCCESS";
export const ADD_MALL_STORE_FAIL = "UPDATE_MALL_STORE_FAIL";

// mall part end

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_MALL_WISE_STORE_BEGIN = "GET_MALL_WISE_STORE_BEGIN";
export const GET_MALL_WISE_STORE_SUCCESS = "GET_MALL_WISE_STORE_SUCCESS";
export const GET_MALL_WISE_STORE_FAIL = "GET_MALL_WISE_STORE_FAIL";

// CUSTOMER

export const CUSTOMER_UPDATE_BEGIN = "CUSTOMER_UPDATE_BEGIN";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";

export const GET_CUSTOMER_BEGIN = "GET_CUSTOMER_BEGIN";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL";

export const CUSSTOMER_UPDATE_BEGIN = "CUSSTOMER_UPDATE_BEGIN";
export const CUSSTOMER_UPDATE_SUCCESS = "CUSSTOMER_UPDATE_SUCCESS";
export const CUSSTOMER_UPDATE_ERROR = "CUSSTOMER_UPDATE_ERROR";

export const GET_REGION_BEGIN = "GET_REGION_BEGIN";
export const GET_REGION_SUCCESS = "GET_REGION_SUCCESS";
export const GET_REGION_FAIL = "GET_REGION_FAIL";

export const REGISTER_CUSTOMER_BEGIN = "REGISTER_CUSTOMER_BEGIN";
export const REGISTER_CUSTOMER_SUCCESS = "REGISTER_CUSTOMER_SUCCESS";
export const REGISTER_CUSTOMER_FAIL = "REGISTER_CUSTOMER_FAIL";

// STORE

export const REGISTER_STORE_BEGIN = "REGISTER_STORE_BEGIN";
export const REGISTER_STORE_SUCCESS = "REGISTER_STORE_SUCCESS";
export const REGISTER_STORE_FAIL = "REGISTER_STORE_FAIL";

export const GET_STORE_BEGIN = "GET_STORE_BEGIN";
export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const GET_STORE_FAIL = "GET_STORE_FAIL";

// update store

export const UPDATE_BRAND_BEGIN = "GET_STORE_BEGIN";
export const UPDATE_BRAND_SUCCESS = "GET_STORE_SUCCESS";
export const UPDATE_BRAND_FAIL = "GET_STORE_FAIL";

// EATERIES

export const GET_EATERIES_BEGIN = "GET_EATERIES_BEGIN";
export const GET_EATERIES_SUCCESS = "GET_EATERIES_SUCCESS";
export const GET_EATERIES_FAIL = "GET_EATERIES_FAIL";

// PRODUCT

export const GET_PRODUCT_BEGIN = "GET_PRODUCT_BEGIN";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const CREATE_PRODUCT_BEGIN = "CREATE_PRODUCT_BEGIN";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_BEGIN = "UPDATE_PRODUCT_BEGIN";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const UPDATE_EATERIES_MALL_BEGIN = "UPDATE_EATERIES_MALL_BEGIN";
export const UPDATE_EATERIES_MALL_SUCCESS = "UPDATE_EATERIES_MALL_SUCCESS";
export const UPDATE_EATERIES_MALL_FAIL = "UPDATE_EATERIES_MALL_BEGIN";

// MALL EVENT

export const GET_MALL_EVENT_BEGIN = "GET_MALL_EVENT_BEGIN";
export const GET_MALL_EVENT_SUCCESS = "GET_MALL_EVENT_SUCCESS";
export const GET_MALL_EVENT_FAIL = "GET_MALL_EVENT_FAIL";

export const CREATE_MALL_EVENT_BEGIN = "CREATE_MALL_EVENT_BEGIN";
export const CREATE_MALL_EVENT_SUCCESS = "CREATE_MALL_EVENT_SUCCESS";
export const CREATE_MALL_EVENT_FAIL = "CREATEMALL_EVENT_FAIL";

export const UPDATE_MALL_EVENT_BEGIN = "UPDATE_MALL_EVENT_BEGIN";
export const UPDATE_MALL_EVENT_SUCCESS = "UPDATE_MALL_EVENT_SUCCESS";
export const UPDATE_MALL_EVENT_FAIL = "UPDATE_MALL_EVENT_FAIL";

// LEADERBOARD

export const GET_LEADERBOARD_BEGIN = "GET_LEADERBOARD_BEGIN";
export const GET_LEADERBOARD_SUCCESS = "GET_LEADERBOARD_SUCCESS";
export const GET_LEADERBOARD_FAIL = "GET_LEADERBOARD_FAIL";

export const CREATE_LEADERBOARD_BEGIN = "CREATE_LEADERBOARD_BEGIN";
export const CREATE_LEADERBOARD_SUCCESS = "CREATE_LEADERBOARD_SUCCESS";
export const CREATE_LEADERBOARD_FAIL = "CREATEMLEADERBOARD_FAIL";

export const UPDATE_LEADERBOARD_BEGIN = "UPDATE_LEADERBOARD_BEGIN";
export const UPDATE_LEADERBOARD_SUCCESS = "UPDATE_LEADERBOARD_SUCCESS";
export const UPDATE_LEADERBOARD_FAIL = "UPDATE_LEADERBOARD_FAIL";

// PROMOTION

export const GET_PROMOTION_BEGIN = "GET_PROMOTION_BEGIN";
export const GET_PROMOTION_SUCCESS = "GET_PROMOTION_SUCCESS";
export const GET_PROMOTION_FAIL = "GET_PROMOTION_FAIL";

export const CREATE_PROMOTION_BEGIN = "CREATE_PROMOTION_BEGIN";
export const CREATE_PROMOTION_SUCCESS = "CREATE_PROMOTION_SUCCESS";
export const CREATE_PROMOTION_FAIL = "CREATEMPROMOTION_FAIL";

export const UPDATE_PROMOTION_BEGIN = "UPDATE_PROMOTION_BEGIN";
export const UPDATE_PROMOTION_SUCCESS = "UPDATE_PROMOTION_SUCCESS";
export const UPDATE_PROMOTION_FAIL = "UPDATE_PROMOTION_FAIL";

// PRODUCTBANNER

export const GET_PRODUCTBANNER_BEGIN = "GET_PRODUCTBANNER_BEGIN";
export const GET_PRODUCTBANNER_SUCCESS = "GET_PRODUCTBANNER_SUCCESS";
export const GET_PRODUCTBANNER_FAIL = "GET_PRODUCTBANNER_FAIL";

export const CREATE_PRODUCTBANNER_BEGIN = "CREATE_PRODUCTBANNER_BEGIN";
export const CREATE_PRODUCTBANNER_SUCCESS = "CREATE_PRODUCTBANNER_SUCCESS";
export const CREATE_PRODUCTBANNER_FAIL = "CREATE_PRODUCTBANNER_FAIL";

export const UPDATE_PRODUCTBANNER_BEGIN = "UPDATE_PRODUCTBANNER_BEGIN";
export const UPDATE_PRODUCTBANNER_SUCCESS = "UPDATE_PRODUCTBANNER_SUCCESS";
export const UPDATE_PRODUCTBANNER_FAIL = "UPDATE_PRODUCTBANNER_FAIL";

// Add Event Mall
export const ADD_EVENT_MALL_BEGIN = "ADD_EVENT_MALL_BEGIN";
export const ADD_EVENT_MALL_SUCCESS = "ADD_EVENT_MALL_SUCCESS";
export const ADD_EVENT_MALL_FAIL = "ADD_EVENT_MALL_FAIL";

// Update Event Mall
export const UPDATE_EVENT_MALL_BEGIN = "UPDATE_EVENT_MALL_BEGIN";
export const UPDATE_EVENT_MALL_SUCCESS = "UPDATE_EVENT_MALL_SUCCESS";
export const UPDATE_EVENT_MALL_FAIL = "UPDATE_EVENT_MALL_FAIL";

// Delete Mall Store
export const DELETE_MALL_STORE_BEGIN = "DELETE_MALL_STORE";
export const DELETE_MALL_STORE_SUCCESS = "DELETE_MALL_STORE_SUCCESS";
export const DELETE_MALL_STORE_FAIL = "DELETE_MALL_STORE_FAIL";

// Delete Mall Eateries
export const DELETE_MALL_EATERIES_BEGIN = "DELETE_MALL_EATERIES_BEGIN";
export const DELETE_MALL_EATERIES_SUCCESS = "DELETE_MALL_EATERIES_SUCESS";
export const DELETE_MALL_EATERIES_FAIL = "DELETE_MALL_EATERIES_FAIL";

// Delete Mall Eateries
export const DELETE_MALL_EVENT_BEGIN = "DELETE_MALL_EVENT_BEGIN";
export const DELETE_MALL_EVENT_SUCCESS = "DELETE_MALL_EVENT_SUCCESS";
export const DELETE_MALL_EVENT_FAIL = "DELETE_MALL_EVENT_FAIL";

// Get Facility Mall
export const GET_MALL_FACILITY_BEGIN = "GET_MALL_FACILITY_BEGIN";
export const GET_MALL_FACILITY_SUCCESS = "GET_MALL_FACILITY_SUCCESS";
export const GET_MALL_FACILITY_ERROR = "GET_MALL_FACILITY_ERROR";

// Update Facility Mall

export const UPDATE_FACILITY_BEGIN = "UPDATE_FACILITY_BEGIN";
export const UPDATE_FACILITY_SUCCESS = "UPDATE_FACILITY_SUCCESS";
export const UPDATE_FACILITY_FAIL = "UPDATE_FACILITY_FAIL";

// Delete Facility Mall

export const DELETE_FACILITY_BEGIN = "DELETE_FACILITY_BEGIN";
export const DELETE_FACILITY_SUCCESS = "DELETE_FACILITY_SUCCESS";
export const DELETE_FACILITY_FAIL = "DELETE_FACILITY_FAIL";

// GET-RETAILER

export const GET_RETAILER_BEGIN = "GET_RETAILER_BEGIN";
export const GET_RETAILER_SUCCESS = "GET_RETAILER_SUCCESS";
export const GET_RETAILER_FAIL = "GET_RETAILER_FAIL";

// Delete Leaderboard
export const DELETE_LEADERBOARD_BEGIN = "DELETE_LEADERBOARD_BEGIN";
export const DELETE_LEADERBOARD_SUCCESS = "DELETE_LEADERBOARD_SUCCESS";
export const DELETE_LEADERBOARD_FAIL = "DELETE_LEADERBOARD_FAIL";

// Delete Promotion bannner
export const DELETE_PROMOTION_BANNER_BEGIN = "DELETE_PROMOTION_BANNER_BEGIN";
export const DELETE_PROMOTION_BANNER_SUCCESS =
  "DELETE_PROMOTION_BANNER_SUCCESS";
export const DELETE_PROMOTION_BANNER_FAIL = "DELETE_PROMOTION_BANNER_FAIL";

// Delete Product banner
export const DELETE_PRODUCT_BANNER_BEGIN = "DELETE_PRODUCT_BANNER_BEGIN";
export const DELETE_PRODUCT_BANNER_SUCCESS = "DELETE_PRODUCT_BANNER_SUCCESS";
export const DELETE_PRODUCT_BANNER_FAIL = "DELETE_PRODUCT_BANNER_FAIL";

// Update Leaderboar banner
export const UPDATE_LEADERBOARD_BANNER_BEGIN =
  "UPDATE_LEADERBOARD_BANNER_BEGIN";
export const UPDATE_LEADERBOARD_BANNER_SUCCESS =
  "UPDATE_LEADERBOARD_BANNER_SUCCESS";
export const UPDATE_LEADERBOARD_BANNER_FAIL = "UPDATE_LEADERBOARD_BANNER_FAIL";

// Update Promotion banner
export const UPDATE_PROMOTION_BANNER_BEGIN = "UPDATE_PROMOTION_BANNER_BEGIN";
export const UPDATE_PRAMOTION_BANNER_SUCCESS =
  "UPDATE_PROMOTION_BANNER_SUCCESS";
export const UPDATE_PRAMOTION_BANNER_FAIL = "UPDATE_PROMOTION_BANNER_FAIL";

// Update Product banner
export const UPDATE_PRODUCT_BANNER_BEGIN = "UPDATE_PRODUCT_BANNER_BEGIN";
export const UPDATE_PRODUCT_BANNER_SUCCESS = "UPDATE_PRODUCT_BANNER_SUCCESS";
export const UPDATE_PRODUCT_BANNER_FAIL = "UPDATE_PRODUCT_BANNER_FAIL";

// Get Category

export const GET_CATEGORY_BEGIN = "GET_CATEGORY_BEGIN";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

// Create Leaderboard Banner

export const CREATE_LEADERBOARD_BANNER_BEGIN =
  "CREATE_LEADERBOARD_BANNER_BEGIN";
export const CREATE_LEADERBANNER_BANNER_SUCCESS =
  "CREATE_LEADERBANNER_BANNER_SUCCESS";
export const CREATE_LEADERBOARD_BANNER_FAIL = "CREATE_LEADERBOARD_BANNER_FAIL";

// Create Promotion Banner

export const CREATE_PROMOTION_BANNER_BEGIN = "CREATE_PROMOTION_BANNER_BEGIN";
export const CREATE_PROMOTION_BANNER_SUCCESS =
  "CREATE_PROMOTION_BANNER_SUCCESS";
export const CREATE_PROMOTION_BANNER_FAIL = "CREATE_PROMOTION_BANNER_FAIL";

// Create Product Banner

export const CREATE_PRODUCT_BANNER_BEGIN = "CREATE_PRODUCT_BANNER_BEGIN";
export const CREATE_PRODUCT_BANNER_SUCCESS = "CREATE_PRODUCT_BANNER_SUCCESS";
export const CREATE_PRODUCT_BANNER_FAIL = "CREATE_PRODUCT_BANNER_FAIL";

// Create ProductTiles Banner

export const CREATE_PRODUCTTILES_BANNER_BEGIN =
  "CREATE_PRODUCTTILES_BANNER_BEGIN";
export const CREATE_PRODUCTTILES_BANNER_SUCCESS =
  "CREATE_PRODUCTTILES_BANNER_SUCCESS";
export const CREATE_PRODUCTTILES_BANNER_FAIL =
  "CREATE_PRODUCTTILES_BANNER_FAIL";

// Delete ProductTiles Banner

export const DELETE_PRODUCTTILES_BANNER_BEGIN =
  "DELETE_PRODUCTTILES_BANNER_BEGIN";
export const DELETE_PRODUCTTILES_BANNER_SUCCESS =
  "DELETE_PRODUCTTILES_BANNER_SUCCESS";
export const DELETE_PRODUCTTILES_BANNER_FAIL =
  "DELETE_PRODUCTTILES_BANNER_FAIL";

// Update ProductTiles Banner

export const UPDATE_PRODUCTTILES_BANNER_BEGIN =
  "UPDATE_PRODUCTTILES_BANNER_BEGIN";
export const UPDATE_PRODUCTRILES_BANNER_SUCCESS =
  "UPDATE_PRODUCTRILES_BANNER_SUCCESS";
export const UPDATE_PRODUCTTILES_BANNER_FAIL =
  "UPDATE_PRODUCTTILES_BANNER_FAIL";

// Get Week

export const GET_WEEK_BEGIN = "GET_WEEK_BEGIN";
export const GET_WEEK_SUCCESS = "GET_WEEK_SUCCESS";
export const GET_WEEK_ERROR = "GET_WEEK_ERROR";

// Get Multiple Mall

export const GET_MULTIPLE_Mall_BEGIN = "GET_MULTIPLE_Mall_BEGIN";
export const GET_MULTIPLE_MALL_SUCCESS = "GET_MULTIPLE_Mall_SUCCESS";
export const GET_MULTIPLE_Mall_ERROR = "GET_MULTIPLE_Mall_ERROR";
